name = "daniel-ma"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "BUDGET_DB"
database_name = "daniel-ma-budget"
database_id = "ad15ccaf-51c6-4523-a8c0-f844cef40ad3"
